### ISSUE TITLE
async function error

### ISSUE THREAD

**Issue by starcraft0429** [5an1ty/kraken-api#3]
```
(async function () {
       ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at babelWatchLoader (/home/ubuntu/Documents/node-postgres-restapi /node_modules/babel-watch/runner.js:50:13)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ubuntu/Documents/node-postgres-restapi /node_modules/babel-watch/runner.js:61:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at process.on (/home/ubuntu/Documents/node-postgres-restapi /node_modules/babel-watch/runner.js:108:21)
```
I noticed async is not supported new version of node.
How can we avoid this?

**Comment by usmankhanic** [comment]
I am experiencing the same issue - any ideas?
